spring:
  application:
    name: eventhorizon
  datasource:
    url: jdbc:mysql://localhost:3306/event_horizon
    username: root
    password: baxter
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      globally_quoted_identifiers: true
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# H2 Database settings for 'test' profile
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
