spring:
  application:
    name: eventhorizon

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:mysql://localhost:3306/event_horizon
    user: root
    password: baxter

  # MySQL Database settings
  datasource:
    url: jdbc:mysql://localhost:3306/event_horizon?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: baxter

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: mysql
    open-in-view: false


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000

server:
  tomcat:
    max-swallow-size: 100MB
