spring:
  application:
    name: eventhorizon

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    url: jdbc:mysql://localhost:3306/event_horizon
    user: root
    password: root

  # MySQL Database settings
  datasource:
    url: jdbc:mysql://localhost:3306/event_horizon?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: mysql
    open-in-view: false


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

server:
  tomcat:
    max-swallow-size: 100MB
